### ISSUE TITLE
Runtime errors on latest

### ISSUE THREAD

**Issue by objectiveSee** [flatlogic/react-native-starter#48]
I get a lot of Red Errors in the Simulator from RN when I run this. Xcode 11.1. "Unknown argument type __attribute__ in method"

<img width="416" alt="Screen Shot 2019-11-04 at 10 56 44 AM" src="https://user-images.githubusercontent.com/1684106/68136697-b2b19000-fef3-11e9-8413-e0a74178504f.png">

**Comment by gaykov** [comment]
Hey!

Did you run the project from the empty directory or did you upgrade? There's a similar issue on RN: https://github.com/facebook/react-native/issues/25154, but it should be fixed in the version we use here.

Can you pls try to run `pod deintegrate && pod install` from `ios` folder and see if it helps?
